services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=local
    ports:
      - 5432:5432
    volumes:
      # - .pq/pg.socket:/var/run/postgresql/.s.PGSQL.5432
      - .pg/pg-socket-dir:/var/run/postgresql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '140MB'
